version: '3.8'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ideastracker
  spring-boot-app:
      build:
        context: ./server
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ideastracker
        SPRING_DATASOURCE_USERNAME: user
        SPRING_DATASOURCE_PASSWORD: root

  react-app:
      build:
        context: ./client
        dockerfile: Dockerfile
      ports:
        - "3000:80"